type CommandResponse {
  code: Int
  message: String
}

type FleetStatistics {
  totalVehicles: Int!
  vehiclesByType: VehicleTypeStats!
  vehiclesByDecade: VehicleDecadeStats!
  vehiclesBySpeedClass: VehicleSpeedClassStats!
  hpStats: HpStats!
  lastUpdated: String!
}

type VehicleTypeStats {
  SUV: Int!
  PickUp: Int!
  Sedan: Int!
  Hatchback: Int!
  Coupe: Int!
}

type VehicleDecadeStats {
  decade1980s: Int!
  decade1990s: Int!
  decade2000s: Int!
  decade2010s: Int!
  decade2020s: Int!
}

type VehicleSpeedClassStats {
  Lento: Int!
  Normal: Int!
  Rapido: Int!
}

type HpStats {
  min: Int!
  max: Int!
  sum: Int!
  count: Int!
  avg: Float!
}

extend type Query {
  ReporterGetFleetStatistics(organizationId: String): FleetStatistics
}

extend type Subscription {
  ReporterFleetStatisticsUpdated: FleetStatistics
}
